version: '3'

services:
  scraping-robo:
    build: .
    shm_size: 1gb
    container_name: scraping-robo
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8081
    env_file:
      - .env
    command: node dist/main
    restart: always
    depends_on:
      - redis
    networks:
      - traefik-net
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.scrapingrobo.rule=Host(`scraping.api.analisesprosolutti.com`)'
      - 'traefik.http.routers.scrapingrobo.entrypoints=websecure'
      - 'traefik.http.routers.scrapingrobo.tls.certresolver=mytlschallenge'
      - 'traefik.http.services.scrapingrobo.loadbalancer.server.port=8081'
    expose:
      - '8081'
    ports:
      - '8081:8081'

  redis:
    image: redis:7
    container_name: redis
    command:
      [
        'redis-server',
        '--save',
        '900',
        '1',
        '--save',
        '300',
        '10',
        '--stop-writes-on-bgsave-error',
        'no',
      ]
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - traefik-net
networks:
  traefik-net:
    external: true

volumes:
  redis-data:
